version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: movie
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432
    networks:
      - network
  mock:
    container_name: mock
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - network
#    links:
#      - postgres

networks:
  network: {}